# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: sudo apt-get install -y blueprint-compiler
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    # TBD
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
      
    - name: Package
      run: dotnet publish -c Release -r linux-x64
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        path: src/WebCamControl.Gtk/bin/Release/net8.0/linux-x64/publish/*
        if-no-files-found: error

